name: Check scalafmt on push

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  scalafmt-lint:
    name: Scalafmt
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Checking your scala code formatting
        uses: GarnerCorp/scalafmt-ci@main
        with:
          args: "--test"
